### PR TITLE
Add missing depends on annotation to promtail and grafana-agent

### PR DESCRIPTION
**Pull request by QuentinBisson**
This PR:

* adds app dependency mechanism to promtail and grafana-agent

### Checklist

- [x] Update changelog in CHANGELOG.md.
- [x] Make sure `values.yaml` and `values.schema.json` are valid.

This will avoid errors like 

```
$ kubectl get app -n $WCNS $WC-grafana-agent -o yaml
[...]
invalid manifest error: (unable to build kubernetes objects from release manifest: resource mapping not found for name: "grafana-agent" namespace: "" from "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
```

### CODE REVIEW

**Comment by marieroque** [comment]
Did you test it on Vintage/CAPI ?

**Comment by QuentinBisson** [comment]
It's ongoing yes

**Review by AndiDog — APPROVED** [review]
Thank you!

**Comment by QuentinBisson** [comment]
Tested on vintage and CAPI

**Pull request merged**
