### PR TITLE
Simplify observability configuration for customers

### PR DESCRIPTION
**Pull request by QuentinBisson**
This PR:

* changes how we configure the observability bundle to align with other bundles in the company towards https://github.com/giantswarm/roadmap/issues/2879

This PR will have a lot of known breaking changes that have to be done before releasing described below:

```[tasklist]
### Changes to do before releasing
- [x] logging-operator promtail enablement https://github.com/giantswarm/logging-operator/pull/60
- [x] renaming prometheus-operator-app to kube-prometheus-stack, waiting for the other 2 to be released first https://github.com/giantswarm/prometheus-operator-app/pull/337 Did not change the repo name yet
- [x] disabling psp disablement on MCs in giantswarm/config https://github.com/giantswarm/config/pull/2001
```

### Checklist

- [x] Update changelog in CHANGELOG.md.
- [x] Make sure `values.yaml` and `values.schema.json` are valid.

### CODE REVIEW

**Comment by QuentinBisson** [comment]
@giantswarm/team-atlas I tested this on CAPI and Vintage but I'd like another pair of eyes especially around cluster upgrade. I'll do an upgrade test tomorrow as well

**Comment by QuentinBisson** [comment]
Upgrade tested and it's working fine but I'd love to have some other eyes cc @giantswarm/team-atlas

**Comment by marieroque** [comment]
✅  Tested on `gaia`, more details here https://github.com/giantswarm/roadmap/issues/2879#issuecomment-1804102392

**Review by marieroque — APPROVED** [review]
LGTM

**Pull request merged**
